# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "db/schema.rb"

# Workaround: AllCops Exclude doesn't reliably filter schema.rb in all contexts
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "db/schema.rb"
